In [1]:
%config IPCompleter.greedy=True


In [2]:
import pandas as pd

df_train = pd.read_csv('train_kaggle.csv')
df_train

Id  label
0          0      0
1          1      0
2          2      0
3          3      0
4          4      0
5          5      0
6          6      0
7          7      0
8          8      1
9          9      0
10        10      1
11        11      0
12        12      0
13        13      0
14        14      1
15        15      0
16        16      0
17        17      1
18        18      0
19        19      0
20        20      0
21        21      1
22        22      0
23        23      0
24        24      0
25        25      0
26        26      0
27        27      1
28        28      0
29        29      0
...      ...    ...
30306  30306      0
30307  30307      0
30308  30308      0
30309  30309      0
30310  30310      0
30311  30311      0
30312  30312      0
30313  30313      0
30314  30314      0
30315  30315      0
30316  30316      0
30317  30317      0
30318  30318      0
30319  30319      0
30320  30320      0
30321  30321      1
30322  30322      0
30323  30323      0
30324  30324      0
30325  30325      0
30326  30326      0
30327  30327      0
30328  30328      0
30329  30329      0
30330  30330      0
30331  30331      0
30332  30332      0
30333  30333      1
30334  30334      0
30335  30335      1

[30336 rows x 2 columns]

In [3]:
import pandas as pd
def load_features(col):
    return pd.read_parquet("filtered_features/filtered_feature{}.gzip".format(col))

In [4]:
import pandas as pd

def load_test_features(col):
    return pd.read_parquet("filtered_test_features/filtered_test_feature{}.gzip".format(col))

In [5]:
NUM_OF_COL = 40

In [6]:
y = df_train['label']
y = y.values
y

array([0, 0, 0, ..., 1, 0, 1], dtype=int64)

In [7]:
load_features(0).shape

(30336, 448)

In [8]:
from sklearn import decomposition
import numpy as np

XTrainAll = []
for col in range(NUM_OF_COL):
    tf = load_features(col)
    XTrainAll.append(tf)
XTrainAll = np.concatenate(XTrainAll,  axis=1)
XTrainAll.shape

(30336, 14564)

In [9]:
XTestAll = []
for col in range(NUM_OF_COL):
    tf = load_test_features(col)
    tf = tf.replace([np.inf], np.finfo('float32').max).replace([np.inf, -np.inf], np.finfo('float32').min).fillna(0)
    XTestAll.append(tf)
XTestAll = np.concatenate(XTestAll,  axis=1)
XTestAll.shape

(10000, 14564)

In [10]:
df_test = pd.read_csv('sample_solution.csv')


In [11]:
y.shape

(30336,)

In [12]:
'''
from sklearn import decomposition

pca = decomposition.PCA(n_components=800)
pca.fit(XTrainAll)
XTrain = pca.transform(XTrainAll)
XTrain.shape
'''
XTrain = XTrainAll

In [13]:
'''
XTest = pca.transform(XTestAll)
XTest.shape
'''
XTest = XTestAll

In [14]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score

gb_clf = GradientBoostingClassifier()
scores = cross_val_score(gb_clf, XTrain, y, cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
scores

Accuracy: 0.96 (+/- 0.01)


array([0.96292024, 0.96192517, 0.96159552, 0.9627493 , 0.9513763 ])

In [15]:
gb_clf.fit(XTrain, y)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              n_iter_no_change=None, presort='auto', random_state=None,
              subsample=1.0, tol=0.0001, validation_fraction=0.1,
              verbose=0, warm_start=False)

In [16]:
probs = gb_clf.predict_proba(XTest)
YTest = probs[:, 0]
YTest

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:38: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:38: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)


array([0.98682112, 0.98736849, 0.9695378 , ..., 0.98251769, 0.99032049,
       0.99099131])

In [17]:
np.max(YTest)

0.9912989596954785

In [18]:
df_test['Predicted'] = YTest
df_test

Id  Predicted
0        0   0.986821
1        1   0.987368
2        2   0.969538
3        3   0.987739
4        4   0.987739
5        5   0.973983
6        6   0.985982
7        7   0.924997
8        8   0.981097
9        9   0.989277
10      10   0.005365
11      11   0.977120
12      12   0.964381
13      13   0.987041
14      14   0.989870
15      15   0.904193
16      16   0.986764
17      17   0.981379
18      18   0.970530
19      19   0.971598
20      20   0.985099
21      21   0.980125
22      22   0.982788
23      23   0.974464
24      24   0.988353
25      25   0.985086
26      26   0.970394
27      27   0.986764
28      28   0.970296
29      29   0.965316
...    ...        ...
9970  9970   0.975426
9971  9971   0.978495
9972  9972   0.967669
9973  9973   0.986449
9974  9974   0.985563
9975  9975   0.978140
9976  9976   0.981823
9977  9977   0.973940
9978  9978   0.886573
9979  9979   0.983683
9980  9980   0.986444
9981  9981   0.987959
9982  9982   0.979225
9983  9983   0.215141
9984  9984   0.990639
9985  9985   0.989171
9986  9986   0.973344
9987  9987   0.987368
9988  9988   0.989812
9989  9989   0.990309
9990  9990   0.979351
9991  9991   0.988776
9992  9992   0.983853
9993  9993   0.962548
9994  9994   0.979060
9995  9995   0.983790
9996  9996   0.941519
9997  9997   0.982518
9998  9998   0.990320
9999  9999   0.990991

[10000 rows x 2 columns]

In [19]:
df_test.to_csv('test.csv', index=False)